---
title: "MN_Log_Model"
author: "Caden"
date: "6/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ISLR)
library(caret)
library(nnet)
```

Use the final dataset that has been cleaned

```{r}
# read in final dataset
# Found in "models" folder in github
data_ratings <- read.csv("FinalDataset_ratings copy.csv")

data_ratings$game_play <- as.character(h_data$game_play)



#Get levels for measuring outcome
#May need to take out some plays (throw aways, spikes, qb kneels etc)

#Get column for pass plays


```


Get the play types that we will try and classify 
```{r}

data_ratings$pass_type <- paste0(data_ratings$pass_length, " ",data_ratings$pass_location)
data_ratings$pass_type <- ifelse(data_ratings$pass_type == "NA NA", NA, data_ratings$pass_type)
data_ratings$pass_type <- ifelse((data_ratings$pass_type == "short right" | data_ratings$pass_type == "short left"),
                                 "short outside", data_ratings$pass_type)
data_ratings$pass_type <- ifelse((data_ratings$pass_type == "deep right" | data_ratings$pass_type == "deep left"),
                                 "deep outside", data_ratings$pass_type)


data_ratings$run_type <- paste0(data_ratings$run_location, " ",data_ratings$run_gap)
data_ratings$run_type <- ifelse(data_ratings$run_type == "NA NA", NA, data_ratings$run_type)
data_ratings$run_type <- ifelse(data_ratings$run_type == "middle NA", "middle", data_ratings$run_type)
data_ratings$run_type <- ifelse((data_ratings$run_type != "middle" & !is.na(data_ratings$run_type)), "outside", data_ratings$run_type)
#Get the play classification 
data_ratings$play_class <- ifelse(is.na(data_ratings$pass_type), data_ratings$run_type, data_ratings$pass_type)

#Drop other plays like special team and stuff
mn_data <- drop_na(data_ratings, play_class)
mn_data <- drop_na(data_ratings, pass)
sum(is.na(mn_data$play_class))
sum(is.na(mn_data$pass))

```


Create the first run/pass model
```{r}


mn_data$play_class <- as.factor(mn_data$play_class)
mn_data$down.x <- as.factor(mn_data$down.x)
mn_data$quarter <- as.factor(mn_data$quarter)
mn_data$isBlitz <- as.factor(mn_data$isBlitz)
#split into train test


#play_index <- createDataPartition(mn_data$play_type, p = 0.7, list = FALSE)
#train_data <- mn_data[play_index, ]
#test_data  <- mn_data[-play_index, ]

#Set short middel pass as the baseline

#train_data$play_class <- relevel(train_data$play_class, ref = "pass short middle")


hier_mod <- glm(pass ~ defendersInTheBox + numDL + numLB + numDB + defRank + isBlitz + totalSacksGame + totalIntGame + avgPassRushers + totalPassBlitzGame + safety_depth + avg_corner_depth
                + chulls+ chulls_ratio, data = mn_data, family = binomial)

#Log odds scale
#My interpretation of logisitc regression coefficients is rusty
summary(hier_mod)


#Exponentiate coefficients
exp(coef(hier_mod))

#Look at original class distributions
# prop.table(table(train_data$pass))

#Evaluate the model
# Predicting the values for train dataset
vars <- mn_data %>%
  select(defendersInTheBox, numDL, numLB, numDB, defRank, isBlitz, totalSacksGame, totalIntGame, avgPassRushers, totalPassBlitzGame, safety_depth, avg_corner_depth, chulls, chulls_ratio)

vars$predicted <- predict(hier_mod, newdata = vars, "response")
vars$real <- mn_data$pass
vars$class <- mn_data$play_class
vars <- drop_na(vars, predicted)


#Look at distribution
plot(density(vars$predicted))

vars$pred_pass <- ifelse(vars$predicted > 0.55, 1,0)
prop.table(table(vars$pred_pass))

# Building classification table
ctable <- table(vars$real, vars$pred_pass)
ctable

# Calculating accuracy - sum of diagonal elements divided by total obs
round((sum(diag(ctable))/sum(ctable))*100,2)


#Include predicted probability in mn class
vars <- drop_na(vars, class)
```

Now add those probabilities into a full multinomial logistic regression 
```{r}

mod_4 <- multinom(class ~ predicted + defendersInTheBox + numDL + numLB + numDB + defRank + isBlitz + totalSacksGame + totalIntGame + avgPassRushers + totalPassBlitzGame + safety_depth + avg_corner_depth+ chulls+ chulls_ratio, data = vars)

#Log odds scale
#My interpretation of logisitc regression coefficients is rusty
summary(mod_4)

#Get z score
z <- summary(mod_4)$coefficients/summary(mod_4)$standard.errors
z

#Get p value
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p

#Exponentiate coefficients
exp(coef(mod_4))

#Look at original class distributions
prop.table(table(vars$class))

#Evaluate the model
# Predicting the values for train dataset
train_vars <- vars %>%
  select(predicted, defendersInTheBox, numDL, numLB, numDB, defRank, isBlitz, totalSacksGame, totalIntGame, avgPassRushers, totalPassBlitzGame, safety_depth, avg_corner_depth, chulls, chulls_ratio)

train_vars$predicted_class <- predict(mod_4, newdata = train_vars, "class")
train_vars$real <- vars$class

# Building classification table
ctable <- table(train_vars$real, train_vars$predicted_class)
ctable

# Calculating accuracy - sum of diagonal elements divided by total obs
round((sum(diag(ctable))/sum(ctable))*100,2)


prop.table(table(train_vars$predicted_class))
prop.table(table(train_vars$real))

```

